#!/bin/sh

set -x
opam install -y . ocamlfind qcheck-core
make -C .. clean look-for-seed
case $? in
  0) exit 0
    ;;
  2) exit 1
    ;;
  *) exit 128 # stop bisection, we did not get the expected failure
    ;;
esac
