#!/bin/bash
# Given some *.pp.ml{,i} files, this will generate *.inc.ml{,i} files
# containing the various chunks that were generated by preprocessing
# If no file is provided, it will look for *.pp.* files in _build

parse() {
  ocamlc -dsource -stop-after parsing "$1" 2>&1
}

keep_ifdef() {
  awk 'BEGIN { chunk=0 } /^#ifdef GENERATED/,/^#endif/ { if($0 ~ /^#ifdef/) { print "#if GENERATED = " chunk++; } else { print } }'
}

case "$1" in
  "--internal")
    for pp in "$@"; do
      base="${pp%%.pp.*}"
      ext="${pp##*.pp.}"
      start="$base.$ext"
      target="${base##_build/default/}"
      if [ -e "$start" ]; then
        diff -D GENERATED <(parse "$start") <(parse "$pp") | keep_ifdef > "$target.inc.$ext"
      fi
    done
    ;;
  "")
    find _build -iname \*.pp.\* | xargs "$0" --internal
    ;;
  *)
    "$0" --internal "$@"
    ;;
esac
