name: Common CI workflow

on:
  workflow_call:
    inputs:
      runs_on:
        description: 'Type of machine + OS on which to run the tests'
        type: string
        default: 'ubuntu-latest'
      compiler:
        description: 'Compiler to use'
        type: string
        default: 'ocaml-base-compiler.5.0.0~beta1'
      compiler_branch:
        description: 'Source branch of the compiler, to set up caching properly (must be set if CI is not using a tagged release of OCaml)'
        type: string
        default: ''
      timeout:
        description: 'Timeout'
        type: number
        default: 180
      only_test:
        description: 'Only test to run (eg “src/array/lin_tests.exe”); whole suite is run if empty'
        type: string
        default: ''
      seed:
        description: 'Seed for the only test'
        type: string
        default: ''
      repeats:
        description: 'Number of test attempts'
        type: string
        default: '10'
      compiler_commit:
        description: 'Version (commit) of the OCaml compiler to use'
        type: string
        default: ''

jobs:
  build-and-test:
    env:
      ONLY_TEST: ${{ inputs.only_test }}
      SEED: ${{ inputs.seed }}
      REPEATS: ${{ inputs.repeats }}
      OCAML_COMPILER_COMMIT: ${{ inputs.compiler_commit }}
      OCAML_COMPILER_BRANCH: ${{ inputs.compiler_branch }}

    runs-on: ${{ inputs.runs_on }}

    timeout-minutes: ${{ inputs.timeout }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Add dummy binaries to $PATH
        run: echo "PATH=$GITHUB_WORKSPACE/.github/bin:$PATH" >> $GITHUB_ENV

      - name: Pick up a robust cache prefix
        id: compute_prefix
        shell: bash
        run: |
          if [ -n "$OCAML_COMPILER_BRANCH" ]; then
            echo "cache_prefix=$(curl -sH "Accept: application/vnd.github.v3+json" "https://api.github.com/repos/ocaml/ocaml/commits/$OCAML_COMPILER_BRANCH" | jq -r .commit.tree.sha)" >> "$GITHUB_OUTPUT"
          else
            echo "cache_prefix=v1" >> "$GITHUB_OUTPUT"
          fi
          cat "$GITHUB_OUTPUT"

      - name: Install OCaml compiler ${{ inputs.compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ inputs.compiler }}
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            alpha: https://github.com/kit-ty-kate/opam-alpha-repository.git
          opam-depext: false
          dune-cache: true
          cache-prefix: ${{ steps.compute_prefix.outputs.cache_prefix }}

      - name: Run the test suite
        run: opam exec -- dune build @src/runner-test/runtest -j1 --no-buffer --display=quiet --cache=disabled --error-reporting=twice
        if: inputs.only_test == ''
