name: Cygwin trunk

on: [push, pull_request, workflow_dispatch]

jobs:
  part1:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.2.0
      cygwin: true
      compiler_git_ref: refs/heads/trunk
      timeout: 360
      dune_alias: 'ci1'

  part2:
    needs: part1
    if: ${{ always() && needs.part1.outputs.skippart2 != 'true' }}
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.2.0
      cygwin: true
      compiler_git_ref: refs/heads/trunk
      timeout: 360
      dune_alias: 'ci2'
