name: Cygwin trunk

on: [push, pull_request, workflow_dispatch]

jobs:
  part1:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.1.0
      cygwin: true
      custom_compiler_version: '5.1.0+trunk-dbd36ae1a5f06a599434f2cca6261aacca4bdf91'
      custom_compiler_src: 'https://github.com/ocaml/ocaml/archive/dbd36ae1a5f06a599434f2cca6261aacca4bdf91.tar.gz'
      timeout: 360
      subsuite: src/array src/atomic src/bigarray src/buffer src/bytes src/domain src/dynlink src/ephemeron src/floatarray src/hashtbl src/io

  part2:
    needs: part1
    if: ${{ always() }}
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.1.0
      cygwin: true
      custom_compiler_version: '5.1.0+trunk-dbd36ae1a5f06a599434f2cca6261aacca4bdf91'
      custom_compiler_src: 'https://github.com/ocaml/ocaml/archive/dbd36ae1a5f06a599434f2cca6261aacca4bdf91.tar.gz'
      timeout: 360
      subsuite: src/lazy src/neg_tests src/queue src/semaphore src/stack src/statistics src/sys src/thread src/threadomain src/weak
