name: Cygwin 5.3

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.3.0
      cygwin: true
      compiler_git_ref: refs/heads/5.3
      timeout: 240
