name: Cygwin trunk

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml.5.4.0
      cygwin: true
      compiler_git_ref: refs/heads/trunk
      timeout: 240
