name: Cygwin 5.1

on: [push, pull_request, workflow_dispatch]

jobs:
  part1:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.0~alpha2+options+win
      cygwin: true
      timeout: 360
      dune_alias: 'ci1'

  part2:
    needs: part1
    if: ${{ always() && needs.part1.outputs.skippart2 != 'true' }}
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.0~alpha2+options+win
      cygwin: true
      timeout: 360
      dune_alias: 'ci2'
