name: Cygwin 5.2

on:
  schedule:
    # Every Monday morning, at 1:11 UTC
    - cron: '11 1 * * 1'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.2.0+options+win
      cygwin: true
      timeout: 240
