name: Automagic

on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use dune
        uses: shym/setup-dune@main
        with:
          automagic: true
