name: Automagic

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ ubuntu-latest, macos-latest, macos-13 ]

    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 180

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use dune
        uses: shym/setup-dune@v0
        with:
          automagic: true
