name: Bytecode 5.2

on:
  schedule:
    # Every Monday morning, at 1:11 UTC
    - cron: '11 1 * * 1'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.2.0+options,ocaml-option-bytecode-only'
      timeout: 240
