name: 32bit 5.1

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.1.0+trunk,ocaml-option-32bit'
      compiler_git_ref: refs/heads/5.1
      timeout: 360
      override_apt_install: bubblewrap gcc-multilib g++-multilib libzstd1:i386 libzstd-dev:i386 pkgconf:i386
