name: Linux 5.1 debug

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-base-compiler.5.1.1'
      dune_profile: 'debug-runtime'
      runparam: 's=4096,v=0,V=1'
      timeout: 240
