name: Linux 5.0.0+trunk bytecode

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.0.0+trunk,ocaml-option-bytecode-only'
      timeout: 360
      only_test: 'src/ephemeron/stm_tests.exe'
      repeats: '200'
      repeats_failfast: true
      compiler_commit: 'f35d5d644234aace39dd3949844ee97085f93da9'
