name: Linux 5.2 debug

on:
  schedule:
    # Every Monday morning, at 1:11 UTC
    - cron: '11 1 * * 1'
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-base-compiler.5.2.0'
      dune_profile: 'debug-runtime'
      runparam: 's=4096,v=0,V=1'
      timeout: 240
