name: Bytecode 5.1

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.1.1+options,ocaml-option-bytecode-only'
      timeout: 240
