name: Linux 5.0.0+trunk bytecode

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.0.0+trunk,ocaml-option-bytecode-only'
      compiler_branch: '5.0'
      timeout: 360
