name: MacOSX 5.0.0+trunk

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.0.0+trunk'
      compiler_branch: '5.0'
      runs_on: 'macos-latest'
