name: MacOSX 5.0.0+trunk

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      compiler: 'ocaml-variants.5.0.0+trunk'
      runs_on: 'macos-latest'
      only_test: 'src/ephemeron/stm_tests.exe'
      seed: '63947905'
      repeats: 5
