name: MinGW bytecode 5.1

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.1+options+win,ocaml-option-mingw,ocaml-option-bytecode-only
      timeout: 240
