name: Test

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OCaml compiler
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0.0

      - name: Build the test
        run: |
          opam exec -- ocamlc -g -o inconsistencies.bc inconsistencies.ml
          opam exec -- ocamlopt -g -o inconsistencies.nat inconsistencies.ml

      - name: Run the native test
        run: |
          ./inconsistencies.nat

      - name: Run the bytecode test
        run: |
          ./inconsistencies.bc
