name: Win bytecode 5.1

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    with:
      runs_on: windows-latest
      compiler: ocaml-variants.5.1.0~alpha2+options,ocaml-option-mingw,ocaml-option-bytecode-only
      timeout: 240
