name: Windows 5.0.0

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    env:
      ONLY_TEST: ''
      SEED: ''
      REPEATS: ''
      QCHECK_MSG_INTERVAL: '60'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install OCaml compiler 5.0 MingW
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ocaml.5.0.0,ocaml-option-mingw
          opam-repositories: |
            dra27: https://github.com/dra27/opam-repository.git#windows-5.0
            default: https://github.com/fdopen/opam-repository-mingw.git#opam2
            override: https://github.com/shym/custom-opam-repository.git#windows
            upstream: https://github.com/ocaml/opam-repository.git
            alpha: https://github.com/kit-ty-kate/opam-alpha-repository.git
          opam-pin: false
          opam-depext: false

      - name: Install Multicore Tests dependencies
        run: |
          #opam pin add "https://github.com/shym/ocamlfind.git#fix-win"
          opam install . --deps-only --with-test

      - name: Show environment
        run: |
          opam exec -- ocamlopt -config
          opam config list
          opam exec -- dune printenv

      - name: Build the test suite
        run: opam exec -- dune build
        if: env.ONLY_TEST == ''

      - name: Run the test suite
        run: opam exec -- dune runtest -j1 --no-buffer --display=quiet --cache=disabled --error-reporting=twice
        if: env.ONLY_TEST == ''

      - name: Run only one test
        run: |
          $ErrorActionPreference = 'Continue'
          $failures = 0
          for($i = 1; $i -le "${env:REPEATS}"; $i++) {
            if("${env:SEED}" -eq "") {
              opam exec -- dune exec "${env:ONLY_TEST}" -- -v
              if($? -eq 0) { $failures += 1 }
            } else {
              opam exec -- dune exec "${env:ONLY_TEST}" -- -v -s "${env:SEED}"
              if($? -eq 0) { $failures += 1 }
            }
          }
          echo "Test failed $failures times"
        if: env.ONLY_TEST != ''
