name: Windows mingw64 common workflow

on:
  workflow_call:
    inputs:
      compiler:
        description: 'Branch or tag of ocaml/ocaml to use as compiler'
        type: string
        default: '5.0.0-beta1'
      only_test:
        description: 'Only test to run (eg “src/array/lin_tests.exe”); whole suite is run if empty'
        type: string
        default: ''
      seed:
        description: 'Seed for the only test'
        type: string
        default: ''
      repeats:
        description: 'Number of test attempts'
        type: string
        default: '2'

jobs:
  build:
    runs-on: windows-latest

    env:
      COMPILER:  ${{ inputs.compiler }}
      ONLY_TEST: ${{ inputs.only_test }}
      SEED: ${{ inputs.seed }}
      REPEATS: ${{ inputs.repeats }}
      QCHECK_MSG_INTERVAL: '60'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install opam etc. with a temporary compiler
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 4.14
          opam-repositories: |
            default: https://github.com/fdopen/opam-repository-mingw.git#opam2
            override: https://github.com/shym/custom-opam-repository.git#windows
            upstream: https://github.com/ocaml/opam-repository.git
            alpha: https://github.com/kit-ty-kate/opam-alpha-repository.git
          opam-pin: false
          opam-depext: false

      - name: Show environment
        run: |
          opam exec -- ocamlopt --version
          opam config list

      - name: Run the test suite
        run: |
          opam install dune
          opam exec -- dune build @src/runner-test/runtest -j1 --no-buffer --display=quiet --cache=disabled --error-reporting=twice
        if: inputs.only_test == ''
